/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    files: File;
    projects: Project;
    frameworks: Framework;
    posts: Post;
    categories: Category;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    frameworks: FrameworksSelect<false> | FrameworksSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'about-page': AboutPage;
    'posts-page': PostsPage;
    seo: Seo;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'posts-page': PostsPageSelect<false> | PostsPageSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  avatar?: (number | null) | Media;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  coverImage: number | Media;
  primaryCallToAction: {
    text: string;
    link: string;
    icon: {
      name: string;
      svg: string;
    };
  };
  secondaryCallToAction: {
    text: string;
    link: string;
    icon: {
      name: string;
      svg: string;
    };
  };
  frameworks?:
    | {
        framework: number | Framework;
        id?: string | null;
      }[]
    | null;
  layout: (
    | OverviewBlock
    | FeatureGridBlock
    | SolutionBlock
    | GalleryBlock
    | ProjectCodeBlock
    | ArchitectureDiagramBlock
    | RichTextBlock
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frameworks".
 */
export interface Framework {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OverviewBlock".
 */
export interface OverviewBlock {
  eyebrow: string;
  summaryTitle: string;
  summaryText: string;
  metadata: {
    heading: string;
    value: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'overview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  eyebrow: string;
  summaryTitle: string;
  cards?: (TechStackFeatureCardBlock | MetricFeatureCardBlock | InformationFeatureCardBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feature-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TechStackFeatureCardBlock".
 */
export interface TechStackFeatureCardBlock {
  columns: '1' | '2' | '3';
  frameworks?: (number | Framework)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tech-stack-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricFeatureCardBlock".
 */
export interface MetricFeatureCardBlock {
  columns: '1' | '2' | '3';
  amount: string;
  label: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metric-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InformationFeatureCardBlock".
 */
export interface InformationFeatureCardBlock {
  columns: '1' | '2' | '3';
  heading: string;
  description: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'information-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionBlock".
 */
export interface SolutionBlock {
  eyebrow: string;
  heading: string;
  features?:
    | {
        icon: {
          name: string;
          svg: string;
        };
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'solution';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  eyebrow: string;
  heading: string;
  layout: '2-column' | '3-column';
  content: {
    media: number | Media;
    captionHeading: string;
    captionText: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectCodeBlock".
 */
export interface ProjectCodeBlock {
  title: {
    eyebrow: string;
    heading: string;
  };
  description: string;
  code: {
    fileLabel: string;
    language:
      'typescript' | 'tsx' | 'javascript' | 'jsx' | 'python' | 'rust' | 'html' | 'css' | 'json' | 'bash' | 'sql';
    code: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'code-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchitectureDiagramBlock".
 */
export interface ArchitectureDiagramBlock {
  title: {
    eyebrow: string;
    heading: string;
  };
  diagram: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'architecture-diagram';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  eyebrow?: string | null;
  heading: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'rich-text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  author: number | User;
  excerpt: string;
  coverImage: number | Media;
  youtubeUrl?: string | null;
  xUrl?: string | null;
  category: number | Category;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'frameworks';
        value: number | Framework;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  coverImage?: T;
  primaryCallToAction?:
    | T
    | {
        text?: T;
        link?: T;
        icon?: T;
      };
  secondaryCallToAction?:
    | T
    | {
        text?: T;
        link?: T;
        icon?: T;
      };
  frameworks?:
    | T
    | {
        framework?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        overview?: T | OverviewBlockSelect<T>;
        'feature-grid'?: T | FeatureGridBlockSelect<T>;
        solution?: T | SolutionBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        'code-block'?: T | ProjectCodeBlockSelect<T>;
        'architecture-diagram'?: T | ArchitectureDiagramBlockSelect<T>;
        'rich-text'?: T | RichTextBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OverviewBlock_select".
 */
export interface OverviewBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  summaryTitle?: T;
  summaryText?: T;
  metadata?:
    | T
    | {
        heading?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  summaryTitle?: T;
  cards?:
    | T
    | {
        'tech-stack-card'?: T | TechStackFeatureCardBlockSelect<T>;
        'metric-card'?: T | MetricFeatureCardBlockSelect<T>;
        'information-card'?: T | InformationFeatureCardBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TechStackFeatureCardBlock_select".
 */
export interface TechStackFeatureCardBlockSelect<T extends boolean = true> {
  columns?: T;
  frameworks?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricFeatureCardBlock_select".
 */
export interface MetricFeatureCardBlockSelect<T extends boolean = true> {
  columns?: T;
  amount?: T;
  label?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InformationFeatureCardBlock_select".
 */
export interface InformationFeatureCardBlockSelect<T extends boolean = true> {
  columns?: T;
  heading?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionBlock_select".
 */
export interface SolutionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  layout?: T;
  content?:
    | T
    | {
        media?: T;
        captionHeading?: T;
        captionText?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectCodeBlock_select".
 */
export interface ProjectCodeBlockSelect<T extends boolean = true> {
  title?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  description?: T;
  code?:
    | T
    | {
        fileLabel?: T;
        language?: T;
        code?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchitectureDiagramBlock_select".
 */
export interface ArchitectureDiagramBlockSelect<T extends boolean = true> {
  title?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  diagram?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frameworks_select".
 */
export interface FrameworksSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  excerpt?: T;
  coverImage?: T;
  youtubeUrl?: T;
  xUrl?: T;
  category?: T;
  content?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: string;
  links: {
    name: string;
    url: string;
    id?: string | null;
  }[];
  resume?: (number | null) | File;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  title: string;
  subtitle?: string | null;
  copyright: string;
  navigationLinks: {
    name: string;
    linkType?: ('custom' | 'file') | null;
    url?: string | null;
    fileDoc?: (number | null) | File;
    id?: string | null;
  }[];
  connectLinks: {
    name: string;
    url: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  content?: (HeroBlock | ProjectBlock | RecentPostsBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heading: string;
  subheading?: string | null;
  actionText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectBlock".
 */
export interface ProjectBlock {
  projects?:
    | {
        project?: (number | null) | Project;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentPostsBlock".
 */
export interface RecentPostsBlock {
  title: string;
  subtitle?: string | null;
  viewAllText: string;
  displayCount: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'recent-posts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heading: string;
  subheading?: string | null;
  portrait?: (number | null) | Media;
  content?: (ValuesBlock | SkillsBlock | ExperienceBlock | HobbiesBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesBlock".
 */
export interface ValuesBlock {
  title: string;
  heading: string;
  description: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'values';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillsBlock".
 */
export interface SkillsBlock {
  title: string;
  heading: string;
  skills?:
    | {
        icon: {
          name: string;
          svg: string;
        };
        title: string;
        technologies: {
          name: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'skills';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExperienceBlock".
 */
export interface ExperienceBlock {
  title: string;
  heading: string;
  jobs?:
    | {
        title: string;
        company: string;
        description: string;
        startDate: string;
        endDate?: string | null;
        current?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'experience';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HobbiesBlock".
 */
export interface HobbiesBlock {
  title: string;
  heading: string;
  description: string;
  tags?:
    | {
        icon: {
          name: string;
          svg: string;
        };
        description: string;
        id?: string | null;
      }[]
    | null;
  firstImage: number | Media;
  secondImage: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hobbies';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-page".
 */
export interface PostsPage {
  id: number;
  title: string;
  subtitle?: string | null;
  featured?: (number | null) | Post;
  postCount: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  title: string;
  description: string;
  /**
   * Used as the Open Graph share image for the Home and About pages.
   */
  profileImage?: (number | null) | Media;
  siteName?: string | null;
  /**
   * Twitter/X handle without the @, e.g. taylorgkelley
   */
  xHandle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  links?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  copyright?: T;
  navigationLinks?:
    | T
    | {
        name?: T;
        linkType?: T;
        url?: T;
        fileDoc?: T;
        id?: T;
      };
  connectLinks?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  content?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        projects?: T | ProjectBlockSelect<T>;
        'recent-posts'?: T | RecentPostsBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  actionText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectBlock_select".
 */
export interface ProjectBlockSelect<T extends boolean = true> {
  projects?:
    | T
    | {
        project?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentPostsBlock_select".
 */
export interface RecentPostsBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  viewAllText?: T;
  displayCount?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  portrait?: T;
  content?:
    | T
    | {
        values?: T | ValuesBlockSelect<T>;
        skills?: T | SkillsBlockSelect<T>;
        experience?: T | ExperienceBlockSelect<T>;
        hobbies?: T | HobbiesBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesBlock_select".
 */
export interface ValuesBlockSelect<T extends boolean = true> {
  title?: T;
  heading?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillsBlock_select".
 */
export interface SkillsBlockSelect<T extends boolean = true> {
  title?: T;
  heading?: T;
  skills?:
    | T
    | {
        icon?: T;
        title?: T;
        technologies?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExperienceBlock_select".
 */
export interface ExperienceBlockSelect<T extends boolean = true> {
  title?: T;
  heading?: T;
  jobs?:
    | T
    | {
        title?: T;
        company?: T;
        description?: T;
        startDate?: T;
        endDate?: T;
        current?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HobbiesBlock_select".
 */
export interface HobbiesBlockSelect<T extends boolean = true> {
  title?: T;
  heading?: T;
  description?: T;
  tags?:
    | T
    | {
        icon?: T;
        description?: T;
        id?: T;
      };
  firstImage?: T;
  secondImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-page_select".
 */
export interface PostsPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  featured?: T;
  postCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  profileImage?: T;
  siteName?: T;
  xHandle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}